### ISSUE TITLE
Missing link from Asset to owner Item after signing STAC Item

### ISSUE THREAD

**Issue by Kirill888** [microsoft/planetary-computer-sdk-for-python#25]
Signed STAC Item returned from `pc.sign` is missing links from Assets back to Item.

```python
assert signed_item.assets[name].owner is item
```

In the example below second assert fails.

```python
from pystac import Item
import planetary_computer as pc

item = Item.from_file("S2B_MSIL2A_20190629T212529_R043_T06VVN_20201006T080531.json")
assert item.assets["B01"].owner is item
signed_item = pc.sign(item)
assert signed_item.assets["B01"].owner is signed_item
```

**Comment by Kirill888** [comment]
When making a clone of an Asset object `.owner` property is reset to `None`. Since Item is fully cloned when signing there is no need to then also clone all the assets. I would suggest adding `in place` signing option to `pc.sign(asset)` that skips cloning of an asset and just modifies passed in object in place, then use that option from `pc.sign(item)` overload.

https://github.com/microsoft/planetary-computer-sdk-for-python/blob/998d18cfc5f8c964c8b07f99d228567851ab5646/planetary_computer/sas.py#L116-L126

**Comment by TomAugspurger** [comment]
Adding an option to skip cloning / operate in place makes sense to me. API-wise, I think we call it either `copy=True/False` or `clone=True/False` (the default being to clone). I guess pystac uses `preserve_dict=True`, but that's in the context of dict -> pystac object.

**Comment by TomAugspurger** [comment]
@Kirill888 do you need a release with #25 in it, or do you have any additional testing / changes before you'd want a release?

**Comment by Kirill888** [comment]
Thanks @TomAugspurger, I'm not in a hurry for these fixes to be released as I ended up signing at url level as that fits for my use case better anyway, but then I'm also not planning any more additions to this, so if you want this fix released sooner that would be great too.

**Comment by TomAugspurger** [comment]
👍 0.4.1 is up on PyPI now https://pypi.org/project/planetary-computer/
