### ISSUE TITLE
ModuleNotFoundError: No module named 'azure'

### ISSUE THREAD

**Issue by julianblue** [microsoft/planetary-computer-sdk-for-python#50]
Hi, 

it seemed that in planetary-computer 0.4.8 a change is causing import error. Issue does not exist in 0.4.7. 

Thanks for looking into it. 
<img width="558" alt="Screenshot 2022-11-03 at 22 57 10" src="https://user-images.githubusercontent.com/21318315/199842150-c0f3c956-65a5-4253-be37-9488633d20f6.png">

**Comment by TomAugspurger** [comment]
Huh, sorry about that. I could have sworn `azure.storage.blob` was a required dependency.

I'll fix this and make a new release.

**Comment by TomAugspurger** [comment]
0.4.9 is out on PyPI and should fix this: https://pypi.org/project/planetary-computer/
